# Generated by Django 2.2.6 on 2019-11-30 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contest',
            old_name='title',
            new_name='sadasd',
        ),
    ]
