# Generated by Django 2.2.6 on 2019-11-30 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0002_auto_20191130_1727'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contest',
            old_name='sadasd',
            new_name='title',
        ),
    ]
