# Generated by Django 2.2.6 on 2019-12-01 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0003_auto_20191130_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='in_files',
            field=models.FileField(blank=True, null=True, upload_to='<function get_contest_code_path at 0x7f74d093c488>/temp'),
        ),
    ]
