# Generated by Django 2.2.6 on 2020-04-02 09:19

import contest.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contest', '0006_contest_out_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classification',
            name='report_file',
        ),
        migrations.RemoveField(
            model_name='contest',
            name='in_files',
        ),
        migrations.RemoveField(
            model_name='contest',
            name='out_files',
        ),
        migrations.AddField(
            model_name='test',
            name='opt_file1',
            field=models.FileField(blank=True, max_length=512, null=True, upload_to=contest.models.get_tests_path),
        ),
        migrations.AddField(
            model_name='test',
            name='opt_file2',
            field=models.FileField(blank=True, max_length=512, null=True, upload_to=contest.models.get_tests_path),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.CreateModel(
            name='UserContestDateException',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('contest', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contest.Contest')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
