"""
Django settings for pandora project.

Generated by 'django-admin startproject' using Django 2.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

from .DB_SetUp import *


BASE_DIR = base_dir()

DB_USER = db_user()
DB_PASSWORD = db_password()
SECRET_KEY = secret_key()

DEBUG = debug()

ALLOWED_HOSTS = hosts()

INSTALLED_APPS = install_apps()

CRISPY_TEMPLATE_PACK = crispy_template_pack()

MIDDLEWARE = middleware()

ROOT_URLCONF = root_urlconf()

TEMPLATES = templates(BASE_DIR)

WSGI_APPLICATION = wsgi_application()

DATABASES = databases(DB_USER, DB_PASSWORD)

AUTH_PASSWORD_VALIDATORS = auth_password_validators()

LANGUAGE_CODE = language_code()

TIME_ZONE = time_zone()

USE_I18N = use_i18n()

USE_L10N = use_l10n()

USE_TZ = use_tz()

STATIC_URL = static_url()


LOCAL_STATIC_CDN_PATH = local_station_cdn_path(BASE_DIR)

STATIC_ROOT = static_root(LOCAL_STATIC_CDN_PATH)
STATICFILES_DIRS = staticfiles_dirs(BASE_DIR)


MEDIA_ROOT = media_root(LOCAL_STATIC_CDN_PATH)
MEDIA_URL = media_url()


LOGIN_REDIRECT_URL = login_redirect_url()
LOGOUT_REDIRECT_URL = logout_redirect_url()
